- name: pushing configs.json
  copy: src="{{ cis_src }}/{{ microservice }}/configs.json" dest="{{ cis_root }}/{{ microservice }}/configs.json"
  when: "inventory_hostname == 'production-server'"

- name: pushing microservice.configs.json
  copy: src={{ microservice }}.configs.json dest="{{ cis_root }}/{{ microservice }}/configs.json"
  when: "inventory_hostname == 'kube-master'"

- name: pushing certs
  command: chdir="{{ cis_root }}" bash -c "cp -r .certs {{ microservice }}/certs"

- name: push binary
  copy: src="{{ cis_src }}/{{ microservice }}/{{ microservice }}"  dest="{{ cis_root }}/{{ microservice }}/{{ microservice }}" mode='0755'
  register: push_res

- name: push Whale's listbank
  copy: src="{{ cis_src }}/whale/listbank.json"  dest="{{ cis_root }}/whale/listbank.json"
  when: "microservice  == 'whale'"
    
- name: push dolphin's zoneinfo.zip
  copy: src="/usr/local/go/lib/time/zoneinfo.zip"  dest="{{ cis_root }}/dolphin/zoneinfo.zip"
  when: "microservice  == 'dolphin'"
    
- name: pushing Dockerfile
  copy: src="{{ cis_src }}/{{ microservice }}/Dockerfile" dest="{{ cis_root }}/{{ microservice }}/Dockerfile"
  when: "inventory_hostname == 'kube-master'"

- name: dockerize service  
  command: chdir="{{ cis_root}}/{{ microservice }}" bash -c "docker build -t {{ microservice }} ./"
