- name: pushing supervisor's conf
  become: yes
  template: src="{{ microservice }}.conf" dest="/etc/supervisor/conf.d/{{ microservice }}.conf"

- name: supervisor reread
  become: yes
  command: "supervisorctl reread"

- name: pushing configs.json
  copy: src="~/go/src/cis/{{ microservice }}/configs.json" dest="{{ cis_root }}/{{ microservice }}/configs.json"
  when: "inventory_hostname != 'test-server'"

- name: pushing test.configs.json
  copy: src=test.configs.json dest="{{ cis_root }}/{{ microservice }}/configs.json"
  when: "inventory_hostname == 'test-server'"

- name: pushing certs
  copy: src="~/go/src/cis/scallops/certs" dest="{{ cis_root }}/{{ microservice }}/"

# begin to push binary
- name: stop service
  become: yes
  command: "supervisorctl stop {{ microservice }}"
  notify: 
    - push binary
    - start service  
