---
- hosts: kube-master
  vars_files: 
    - ../common.vars
  tasks:
      - name: Pushing certs
        copy: src=../certs/ dest="/home/{{ ansible_user }}/go/src/cis/.certs"
      - name: Dockerizing microservices
        with_items: "{{ microservices }}"
        include_role:
            name: dockerizer
        vars:
            microservice: "{{ item }}"
