---
- hosts: test-server
  roles:
    - daemons
      #######
    - dolphin
    - saba
    - octopus
      #######
    - poseidon
    - seabed
    - seahorse
    - tuna
      #######
    - mackerel
    - xevipham
    - seaweed
      #######
    - viettel
    - mobifone
    - vinaphone
    - vietnamobile
    - taodo
    - napas
      #######
    - jellyfish
    - whale
